# version: '3'
services:
  service1:
    build:
      context: .
      dockerfile: ServiceA/Dockerfile
    image: servicea:latest
    ports:
      - "8081:8080"

  service2:
    build:
      context: .
      dockerfile: FrontendService/Dockerfile
    image: frontendservice:latest
    ports:
      - "8082:8080"
    environment:
      - backendservice=http://service3:8080
